apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPFlexVolumes
metadata:
  name: psp-flexvolume-drivers
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedFlexVolumes:
    - driver: "azure/blobfuse"
    - driver: "microsoft.com/smb"
