apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPPrivilegedContainer
metadata:
  name: psp-privileged-container
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: ["kube-system", "kubeflow", "istio-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
