apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPFSGroup
metadata:
  name: psp-fsgroup
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: ["kube-system", "kubecost", "kubeflow", "istio-system", "monitoring"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    rule: "MayRunAs" #"MustRunAs" #"MayRunAs", "RunAsAny"
    ranges:
    - min: 1
      max: 1000
