apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPHostNetworkingPorts
metadata:
  name: psp-host-network-ports
spec:
  match:
    excludedNamespaces: ["gconfid"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    hostNetwork: true
    min: 9100
    max: 9900
