apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerLimits
metadata:
  name: container-limits
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: ["kube-system", "kubeflow", "istio-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "200m"
    memory: "1Gi"
