apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPCapabilities
metadata:
  name: psp-capabilities
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: ["kube-system", "kubeflow", "istio-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedCapabilities: ["something"]
    requiredDropCapabilities: ["must_drop"]
