apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerAllowedImages
metadata:
  name: container-allowed-images
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    repos:
      # StatCan Repository
      - 'artifactory.cloud.statcan.ca/'
      - 'k8scc01covidacr.azurecr.io/'
      - 'statcan/'

      # Temporary
      - 'sylus/gitlab-ci'
      - 'python'
      - 'docker:'
      - 'certbot/'
      - 'aquasec/'
      - 'cachethq/docker:'
      - 'docker.io/postgres:'
      - 'bitnami/matomo'
      - 'bitnami/matomo:'
      - 'bitnami/kubectl'
      - 'bitnami/kubectl:'
      - 'bitnami/redis:'
      - 'redis:'
      - 'microsoft/mssql-server-linux:'
      - 'postgres:'
      - 'docker.io/bitnami/redis:'
      - 'fluentd:'
      - 'containous/whoami'
      - 'docker.bintray.io/bitnami/postgresql:'
      - 'docker.bintray.io/jfrog/'
      - 'notary:'
      - 'solr:'
      - 'docker.io/bitnami/pgpool:'
      - 'zookeeper:'
      - 'govcloud/'
      - 'jupyter/'
      - 'jupyterhub/'
      - 'quay.io/awesomenix/drainsafe-manager'
      - 'gcr.io/google_samples/k8szk:v3'
      - 'appropriate/curl'
      - 'atlassian/'
      - 'drupalwxt/'
      - 'gitlab/'
      - 'lucidworks/'
      - 'hairyhenderson/'
      - 'notary/'
      - 'sqlpad/'
      - 'k8s.gcr.io/'
      - 'nginx'

      # Base containers
      - 'alpine:'
      - 'library/alpine'
      - 'bash:'
      - 'library/bash'
      - 'python:'
      - 'library/python'
      - 'sha256:'
      - 'library/sha256'
      - 'busybox'
      - 'busybox:'
      - 'library/busybox'

      # Istio
      - 'istio/'
      - 'docker.io/istio/'
      - 'quay.io/kiali/'

      # Elastic
      - 'docker.elastic.co/'

      # Prometheus + Grafana
      - 'prom/'
      - 'docker.io/prom/'
      - 'grafana/'
      - 'kiwigrid/k8s-sidecar'
      - 'quay.io/coreos/'
      - 'quay.io/prometheus/'

      # Cert manager
      - 'quay.io/jetstack/'

      # Open Policy Agent
      - 'quay.io/open-policy-agent/'
      - 'openpolicyagent/opa'

      # Fluentd
      - 'jvassev/kube-fluentd-operator'

      # Hashicorp
      - 'vault:'
      - 'hashicorp/'

      # Pachyderm
      - 'pachyderm/'

      # Helm (Tiller)
      - 'gcr.io/kubernetes-helm/'

      # Velero
      - 'gcr.io/heptio-images/'

      # Kubecost
      - 'gcr.io/kubecost1/'
      - 'jimmidyson/configmap-reload:'

      # Kubeflow
      - 'argoproj/'
      - 'seldonio/'
      - 'docker.io/seldonio/'
      - 'gcr.io/google_containers/'
      - 'gcr.io/kf-pipeline-contrib/'
      - 'gcr.io/kfserving/'
      - 'gcr.io/knative-releases/'
      - 'gcr.io/kubebuilder/'
      - 'gcr.io/kubeflow-images-public/'
      - 'gcr.io/ml-pipeline/'
      - 'gcr.io/spark-operator/'
      - 'gcr.io/tfx-oss-public/'
      - 'google/cloud-sdk'
      - 'metacontroller/'
      - 'tensorflow/'

      # Volcano
      - 'docker.io/volcanosh/'
      - 'volcanosh/'

      # Data
      - 'minio/'
      - 'mysql:'
      - 'bitnami/postgresql'
      - 'bitnami/minideb'
      - 'docker.io/bitnami/mariadb'
      - 'docker.io/bitnami/postgresql'
      - 'docker.io/bitnami/minideb'

      # Dremio
      - 'dremio/'
      - 'k8s.gcr.io/kubernetes-zookeeper'

      # Web servers
      - 'nginx:'

      # AKS
      - 'deis/hcp-tunnel-front'
      - 'mcr.microsoft.com/'
      - 'nvidia/'

      # Velero
      - 'velero'

      # Utilities
      - 'zachomedia/minio'
      - 'zachomedia/etcd'
      - 'zachomedia/kubernetes-sidecar-terminator'
      - 'zachomedia/gitlab-runner'
