apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPHostNamespace
metadata:
  name: psp-host-namespace
spec:
  match:
    excludedNamespaces: ["cloudops", "kubecost", "kube-system", "monitoring", "starboard"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
