apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPHostFilesystem
metadata:
  name: psp-host-filesystem
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: ["kube-system", "kubeflow", "istio-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPaths:
    - readOnly: true
      pathPrefix: "/foo"
