apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PSPHostFilesystem
metadata:
  name: psp-host-filesystem
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: ["kube-system", "kubeflow", "istio-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPaths:
    - readOnly: true
      pathPrefix: "/etc/kubernetes/azure.json"
    - readOnly: true
      pathPrefix: "/etc/kubernetes/certs"
    - readOnly: true
      pathPrefix: "/run/xtables.lock"
    - readOnly: true
      pathPrefix: "/var/lib/kubelet/device-plugins"
