apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LoadBalancerNoPublicIPs
metadata:
  name: loadbalancer-no-public-ips
spec:
  match:
    excludedNamespaces: "istio-system"
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
